### ISSUE TITLE
Issue about Attribute Inference Attack/Defense in Privacy Field

### ISSUE THREAD

**Issue by icmpnorequest** [ChrisWaites/pyvacy#1]
Hi Chris,
Thank you for your codes in privacy algorithm implemented in Pytorch. I'm a new learner in Privacy field and I'm studying attribute inference / membership inference. TensorFlow Privacy repository mainly includes privacy algorithms in DP.  However, it includes few codes about attribute inference privacy. 

Could you upload some codes about attribute / membership inference  in the future?

Thanks in advance!

**Comment by ChrisWaites** [comment]
Sorry to have not gotten back about this - it's on the radar!
